/* testvectors_aes_basic.c
 *
 * Description: Test vectors for AES, for key sizes 128, 192 and 256 bits
 *              and ECB, CBC and CTR modes.
 */

/*****************************************************************************
* Copyright (c) 2014-2017 INSIDE Secure B.V. All Rights Reserved.
*
* This confidential and proprietary software may be used only as authorized
* by a licensing agreement from INSIDE Secure.
*
* The entire notice above must be reproduced on all authorized copies that
* may only be made to the extent permitted by a licensing agreement from
* INSIDE Secure.
*
* For more information or support, please go to our online support system at
* https://customersupport.insidesecure.com.
* In case you do not have an account for this system, please send an e-mail
* to ESSEmbeddedHW-Support@insidesecure.com.
*****************************************************************************/

#include "basic_defs.h"

#include "testvectors_aes_basic.h"

/* Actual vectors, from automatically generated file. */
#include "testvectors_aes_basic_data.h"

/* Macros used to build hash_test_vectors. */

#define TEST_VECTOR_AES(mode, key, ptx, ctx, iv) \
    {                                            \
        TESTVECTORS_MODE_##mode,                 \
        key, ptx, ctx, iv,                       \
        sizeof(key), sizeof(ptx)                 \
    }


static const TestVector_AES_BASIC_Rec_t aes_basic_test_vectors [] =
{
/* autogenerated section begin */
    TEST_VECTOR_AES(ECB, F_1_1_key, F_1_1_ptx, F_1_1_ctx, NULL),
    //TEST_VECTOR_AES(ECB, F_1_3_key, F_1_3_ptx, F_1_3_ctx, NULL),
    //TEST_VECTOR_AES(ECB, F_1_5_key, F_1_5_ptx, F_1_5_ctx, NULL),
    //TEST_VECTOR_AES(CBC, F_2_1_key, F_2_1_ptx, F_2_1_ctx, F_2_1_iv),
    TEST_VECTOR_AES(CBC, F_2_3_key, F_2_3_ptx, F_2_3_ctx, F_2_3_iv),
    //TEST_VECTOR_AES(CBC, F_2_5_key, F_2_5_ptx, F_2_5_ctx, F_2_5_iv),
    //TEST_VECTOR_AES(CTR, F_5_1_key, F_5_1_ptx, F_5_1_ctx, F_5_1_iv),
    TEST_VECTOR_AES(CTR, F_5_3_key, F_5_3_ptx, F_5_3_ctx, F_5_3_iv),
    //TEST_VECTOR_AES(CTR, F_5_5_key, F_5_5_ptx, F_5_5_ctx, F_5_5_iv),
    //TEST_VECTOR_AES(ICM, F_4_1_key, F_4_1_ptx, F_4_1_ctx, F_4_1_iv),
    //TEST_VECTOR_AES(ICM, F_4_2_key, F_4_2_ptx, F_4_2_ctx, F_4_2_iv)
/* autogenerated section end */
};

/* The function API for accessing the vectors. */

int
test_vectors_aes_basic_num(void)
{
    return sizeof(aes_basic_test_vectors) / sizeof(aes_basic_test_vectors[0]);
}

TestVector_AES_BASIC_t
test_vectors_aes_basic_get(int Index)
{
    if (Index >= test_vectors_aes_basic_num())
        return NULL;

    return &aes_basic_test_vectors[Index];
}

void
test_vectors_aes_basic_release(TestVector_AES_BASIC_t Vector_p)
{
    /* Test vectors are statically defined => nothing to do. */
    IDENTIFIER_NOT_USED(Vector_p);
}

/* end of file testvectors_aes_basic.c */
